#define CONTACT_FILTER_ANYTHING 1 << 0
#define CONTACT_FILTER_ENEMY 1 << 1
#define CONTACT_FILTER_ENVIORNMENT 1 << 2
#define CONTACT_FILTER_INTERACTABLE 1 << 3
#define CONTACT_FILTER_PLAYER 1 << 4
#define CONTACT_FILTER_ENVIORNMENT_OBJECT_OUTLINE 1 << 5
#define CONTACT_FILTER_NPC 1 << 6

